### ISSUE TITLE
Support for EO Mini Pro version 1

### ISSUE THREAD

**Issue by inifinityandbeyond** [twhittock/eo_mini#13]
Hi.  Am I right that this development will not support the version 1 EV charger (used to connect via Enel X, or e-motorwerks) ?

**Comment by twhittock** [comment]
Hi, unless there's someone who wants to provide a PR for a version which works for that model, then I doubt it... This is a hobby project added because I have the mini and wanted it integrated into HA, I don't even really know how people managed to work out the API calls for the mini itself, I just integrated them together.
